# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'destiny' do
   pod 'AFNetworking', '~> 3.1.0'
   pod 'Wonderful', '~> 1.2.0'
   pod 'YYModel', '~> 1.0.4'
  target 'destinyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'destinyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
